# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       Freiertag

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    Little application to show german holidays.
Version:    1.0
Release:    1
Group:      Qt/Qt
License:    GPL3
Source0:    %{name}-%{version}.tar.bz2
Source100:  Freiertag.yaml
Requires:   sailfishsilica-qt5
BuildRequires:  pkgconfig(sailfishapp)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  desktop-file-utils

%description
This application allows you to show german holidays by just selecting a year and a german federal state. You can select between school holidays, mandatory holidays and all holidays.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
/usr/share/Freiertag/data/2013/feiertage
/usr/share/Freiertag/data/2013/ferien
%{_datadir}/%{name}/qml
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/90x90/apps/%{name}.png
/usr/bin
/usr/share/Freiertag
/usr/share/applications
/usr/share/icons/hicolor/90x90/apps
%{_datadir}/Freiertag/data/2013/ferien
%{_datadir}/Freiertag/data/2013/feiertage
%{_datadir}/Freiertag/data/2014/ferien
%{_datadir}/Freiertag/data/2014/feiertage
%{_datadir}/Freiertag/data/2015/ferien
%{_datadir}/Freiertag/data/2015/feiertage
/usr/share/Freiertag/data/2014/ferien
/usr/share/Freiertag/data/2014/feiertage
/usr/share/Freiertag/data/2015/ferien
/usr/share/Freiertag/data/2015/feiertage
# >> files
# << files
